####################################################
# "External" Keystone service with own MySQL in
# an own network (MySQL not accessible from outside).
# Only Keystone ports 5000 and 35357 are accessible.
# !!!! Configure .env !!!!
####################################################
version: '2'
services:

  mysql_keystone:
    hostname: keystone-host
    image: mysql:${MYSQL_VERSION}
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: secretmysql
      LOGSTASH_FIELDS: "service=mysql_keystone"
    networks:
      - network_keystone

  mysql-init_keystone:
    hostname: keystone-host
    image: fest/mysql-init:${MYSQL_INIT_VERSION}
    environment:
      CREATE_MON_USERS: "false"
      GRAFANA_DB_ENABLED: "false"
      MYSQL_INIT_HOST: mysql_keystone
      MYSQL_INIT_DISABLE_REMOTE_ROOT: "false"
      MYSQL_INIT_RANDOM_PASSWORD: "false"
      LOGSTASH_FIELDS: "service=mysql_keystone-init"
    networks:
      - network_keystone
    depends_on:
      - mysql_keystone

  keystone:
    hostname: keystone-host
    image: fest/keystone:${MON_KEYSTONE_VERSION}
    restart: on-failure
    environment:
      KEYSTONE_HOST: ${MON_KEYSTONE_IP_ADDR}
      KEYSTONE_PASSWORD: secretadmin
      KEYSTONE_DATABASE_BACKEND: mysql
      KEYSTONE_MYSQL_HOST: mysql_keystone
      KEYSTONE_MYSQL_USER: keystone
      KEYSTONE_MYSQL_PASSWORD: keystone
      KEYSTONE_MYSQL_DATABASE: keystone
      KEYSTONE_MONASCA_ENDPOINT: ${MON_MONASCA_API_URL}
      LOGSTASH_FIELDS: "service=keystone"
    depends_on:
      - mysql_keystone
    ports:
      - "5000:5000"
      - "35357:35357"
    networks:
      - network_keystone

  horizon:
    hostname: horizon-host
    image: fest/horizon:${HORIZON_VERSION}
    restart: on-failure
    environment:
      MON_KEYSTONE_URL: ${MON_KEYSTONE_URL}
      GRAFANA_URL: ${MON_GRAFANA_URL}
    depends_on:
      - keystone
    ports:
      - "80:80"
    networks:
      - network_keystone
   
networks:
  network_keystone:
    driver: bridge
